/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Database.HopDongDB;
import Model.HopDong;
import java.awt.List;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Khach
 */
public class HopDongView extends javax.swing.JFrame {

    /**
     * Creates new form HopDongView
     */
    public DefaultTableModel model;
    ArrayList<HopDong> list;
    int index;

    public HopDongView() {
        initComponents();
    }

    private void ShowTable() {
        model = (DefaultTableModel) TableModel.getModel();
        model.setRowCount(0);
        list = new HopDongDB().listHopDong();
        for (HopDong hd : list) {
            model.addRow(new Object[]{hd.getID(), hd.getTen(), hd.getNgayBatDau(), hd.getNgayKetThuc(),
                hd.isGiaHan(), hd.getSolanky(), hd.getMaNV()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableModel = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ngaybatdau = new javax.swing.JTextField();
        ngayketthuc = new javax.swing.JTextField();
        lanky = new javax.swing.JTextField();
        xoa = new javax.swing.JButton();
        sua = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        manv = new javax.swing.JTextField();
        them = new javax.swing.JButton();
        no = new javax.swing.JTextField();
        Timkiem = new javax.swing.JButton();
        Indanhsach = new javax.swing.JButton();
        ID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Ten = new javax.swing.JComboBox<>();
        langiahan = new javax.swing.JComboBox<>();
        TimTheoMa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        nhansu = new javax.swing.JCheckBoxMenuItem();
        phongban = new javax.swing.JCheckBoxMenuItem();
        luong = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Ten", "NgayBatDau", "NgayKetThuc", "GiaHan", "SoLanKy", "MaNV"
            }
        ));
        TableModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableModelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableModel);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Ngày bắt đầu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Ngày kết thúc");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Gia hạn");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Số lần ký");

        ngayketthuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ngayketthucActionPerformed(evt);
            }
        });

        lanky.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lankyActionPerformed(evt);
            }
        });

        xoa.setText("Xóa");
        xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaActionPerformed(evt);
            }
        });

        sua.setText("Sửa");
        sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Mã nhân viên");

        manv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manvActionPerformed(evt);
            }
        });

        them.setText("Thêm");
        them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themActionPerformed(evt);
            }
        });

        Timkiem.setText("Tìm");
        Timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimkiemActionPerformed(evt);
            }
        });

        Indanhsach.setText("In");
        Indanhsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndanhsachActionPerformed(evt);
            }
        });

        ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("ID:");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Tên hợp đồng:");

        Ten.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hợp đồng lao động", "Hợp đồng ngắn hạn", "Hợp đồng dài hạn", "Hợp đồng thử việc", "Hợp đồng cộng tác" }));

        langiahan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Có", "Không" }));

        TimTheoMa.setText("Tìm theo mã nhân viên");
        TimTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimTheoMaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                            .addComponent(xoa)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(ngaybatdau, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                        .addComponent(ngayketthuc)
                                        .addComponent(lanky)
                                        .addComponent(manv)
                                        .addComponent(ID, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
                                    .addComponent(langiahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Indanhsach))))
                    .addComponent(them)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Timkiem)
                        .addGap(18, 18, 18)
                        .addComponent(TimTheoMa))
                    .addComponent(sua))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(592, 592, 592))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Ten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ngaybatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ngayketthuc, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(langiahan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lanky, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(no, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Timkiem)
                            .addComponent(TimTheoMa))
                        .addGap(18, 18, 18)
                        .addComponent(sua)
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(xoa)
                            .addComponent(Indanhsach))
                        .addGap(33, 33, 33)
                        .addComponent(them))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(334, Short.MAX_VALUE))
        );

        jMenu1.setText("Menu");

        nhansu.setSelected(true);
        nhansu.setText("Quản lý nhân sự");
        nhansu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhansuActionPerformed(evt);
            }
        });
        jMenu1.add(nhansu);

        phongban.setSelected(true);
        phongban.setText("Quản lý phòng ban");
        phongban.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phongbanActionPerformed(evt);
            }
        });
        jMenu1.add(phongban);

        luong.setSelected(true);
        luong.setText("Tính lương");
        luong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luongActionPerformed(evt);
            }
        });
        jMenu1.add(luong);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(142, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ngayketthucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ngayketthucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ngayketthucActionPerformed

    private void lankyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lankyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lankyActionPerformed

    private void manvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_manvActionPerformed

    private void themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themActionPerformed
        // TODO add your handling code here:
        if (Check()) {
            HopDong hd = new HopDong();
            hd.setID(ID.getText());
            hd.setTen(Ten.getSelectedItem().toString());
            hd.setNgayBatDau(ngaybatdau.getText());
            hd.setNgayKetThuc(ngayketthuc.getText());
            if (langiahan.getSelectedIndex() == 0) {
                hd.setGiaHan(true);
            } else {
                hd.setGiaHan(false);
            }
            hd.setSolanky(Integer.parseInt(lanky.getText()));
            hd.setMaNV(manv.getText());
            HopDongDB dbl = new HopDongDB();
            dbl.addHopDong(hd);
            ShowTable();
        } else {
            JOptionPane.showMessageDialog(null, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_themActionPerformed

    private void IndanhsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndanhsachActionPerformed
        // TODO add your handling code here:
        ShowTable();
    }//GEN-LAST:event_IndanhsachActionPerformed

    private void TableModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableModelMouseClicked
        // TODO add your handling code here:
        index = TableModel.getSelectedRow();
        HopDong hd = list.get(index);
        ID.setText(hd.getID());
        ngaybatdau.setText(hd.getNgayBatDau());
        ngayketthuc.setText(hd.getNgayKetThuc());
        langiahan.setSelectedItem(hd.isGiaHan());
        lanky.setText(hd.getSolanky() + "");
        manv.setText(hd.getMaNV());
        Ten.setSelectedItem(hd.getTen());
    }//GEN-LAST:event_TableModelMouseClicked

    private void IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDActionPerformed

    private void xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaActionPerformed
        // TODO add your handling code here:
        index = TableModel.getSelectedRow();
        HopDong hd = list.get(index);
        int ch = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa hợp đồng này", "Thông báo", JOptionPane.YES_NO_OPTION);
        if (ch == JOptionPane.YES_OPTION) {            
            HopDongDB dbl = new HopDongDB();
            dbl.DeleteHD(hd.getMaNV());
            ShowTable();
        }
        ShowTable();
    }//GEN-LAST:event_xoaActionPerformed

    private void TimkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimkiemActionPerformed
        // TODO add your handling code here:
        String a = no.getText();
        model = (DefaultTableModel) TableModel.getModel();
        if (a.length() > 0) {
            list = new HopDongDB().FindByName(a);
            model.setRowCount(0);
            for (HopDong hd : list) {
                model.addRow(new Object[]{hd.getID(), hd.getTen(), hd.getNgayBatDau(), hd.getNgayKetThuc(),
                    hd.isGiaHan(), hd.getSolanky(), hd.getMaNV()});
            }
        }
    }//GEN-LAST:event_TimkiemActionPerformed

    private void suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaActionPerformed
        // TODO add your handling code here:
        try {
            index = TableModel.getSelectedRow();
            HopDong hd = list.get(index);
            new HopDongDB().DeleteHD(hd.getID());
            if (Check()) {
                hd.setID(ID.getText());
                hd.setTen(Ten.getSelectedItem().toString());
                hd.setNgayBatDau(ngaybatdau.getText());
                hd.setNgayKetThuc(ngayketthuc.getText());
                if (langiahan.getSelectedIndex() == 0) {
                    hd.setGiaHan(true);
                } else {
                    hd.setGiaHan(false);
                }
                hd.setSolanky(Integer.parseInt(lanky.getText()));
                hd.setMaNV(manv.getText());
                HopDongDB dbl = new HopDongDB();
                dbl.addHopDong(hd);
                ShowTable();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Thông tin không hợp lệ");
        }
    }//GEN-LAST:event_suaActionPerformed

    private void phongbanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phongbanActionPerformed
        // TODO add your handling code here:
        new PhongBanView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_phongbanActionPerformed

    private void luongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luongActionPerformed
        // TODO add your handling code here:
         new Tinhluong().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_luongActionPerformed

    private void nhansuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhansuActionPerformed
        // TODO add your handling code here:
         new NhanVienView().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhansuActionPerformed

    private void TimTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimTheoMaActionPerformed
        // TODO add your handling code here:
        String a = manv.getText();
        model = (DefaultTableModel) TableModel.getModel();
        if (a.length() > 0) {
            list = new HopDongDB().FindByName1(a);
            model.setRowCount(0);
            for (HopDong hd : list) {
                model.addRow(new Object[]{hd.getID(), hd.getTen(), hd.getNgayBatDau(), hd.getNgayKetThuc(),
                    hd.isGiaHan(), hd.getSolanky(), hd.getMaNV()});
            }
        }
        
    }//GEN-LAST:event_TimTheoMaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HopDongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HopDongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HopDongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HopDongView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HopDongView().setVisible(true);
            }
        });
    }

    public boolean Check() {
        double a = Double.parseDouble(Xu(ngaybatdau.getText()));
        double b = Double.parseDouble(Xu(ngayketthuc.getText()));
        String c = lanky.getText().toString();        
        if (a >= b) {
            return false;
        }
        if(ID.getText().toString().length() <= 0 || manv.getText().toString().length() <= 0){
            return false;
        }
        for (int i = 0; i < c.length(); i++) {
            if (Character.isLetter(c.charAt(i))) {
                return false;
            }
        }
        return true;
    }

    public String Xu(String a) {
        String chuoi = "";
        for (int i = 0; i < a.length(); i++) {
            if (Character.isDigit(a.charAt(i))) {
                chuoi += a.charAt(i);
            }
        }
        return chuoi;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ID;
    private javax.swing.JButton Indanhsach;
    private javax.swing.JTable TableModel;
    private javax.swing.JComboBox<String> Ten;
    private javax.swing.JButton TimTheoMa;
    private javax.swing.JButton Timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> langiahan;
    private javax.swing.JTextField lanky;
    private javax.swing.JCheckBoxMenuItem luong;
    private javax.swing.JTextField manv;
    private javax.swing.JTextField ngaybatdau;
    private javax.swing.JTextField ngayketthuc;
    private javax.swing.JCheckBoxMenuItem nhansu;
    private javax.swing.JTextField no;
    private javax.swing.JCheckBoxMenuItem phongban;
    private javax.swing.JButton sua;
    private javax.swing.JButton them;
    private javax.swing.JButton xoa;
    // End of variables declaration//GEN-END:variables
}
